config/routes.rb
Erms::Application.routes.draw do
    
    root :to => 'home#index'
    get "log_in" => "sessions#new", :as => "log_in"
    get "log_out" => "sessions#destroy", :as => "log_out"
    get "/resources/search" => "resources#search", :as => "search"
    get "/resources/status" => "resources#status", :as => "status"
    get "/resources/report" => "resources#report", :as => "report"
    match "/requests/deploy" => "requests#deploy", :as => "deploy"
    match "/requests/deploy_request" => "requests#deploy_request", :as => "deploy_request"
    match "/requests/make_request" => "requests#make_request", :as => "make_request"
    match "/requests/return" => "requests#return", :as => "return"
    match "/requests/reject" => "requests#reject", :as => "reject"
    match "/resources/search_results" => "resources#search_results", :as => "search_results"
    resources :sessions    
    resources :users

    resources :resources

    resources :requests

    resources :municipalities

    resources :incidents

    resources :governmentagencies

    resources :esfs

    resources :costperitems

    resources :companies

    resources :capabilities

    resources :addesfs

end

app/models/incident.rb
class Incident < ActiveRecord::Base
    belongs_to :user
    validates_presence_of :this_date, :description, :lat, :lon, :user_id
    validates_inclusion_of :lat, :in => -90..90, :message => "Lat must be in [-90,90]"
    validates_inclusion_of :lon, :in => -90..90, :message => "Lon must be in [-90,90]"
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_filter :check_login
  # GET /incidents
  # GET /incidents.json
  def index
    @incidents = Incident.find_by_sql("SELECT * FROM incidents")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @incidents }
    end
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
    @incident = Incident.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @incident }
    end
  end

  # GET /incidents/new
  # GET /incidents/new.json
  def new
    @incident = Incident.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @incident }
    end
  end

  # GET /incidents/1/edit
  def edit
    @incident = Incident.find(params[:id])
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(params[:incident])
    @incident.user_id = current_user.id
    respond_to do |format|
      if @incident.save
        format.html { redirect_to root_path( notice: 'Incident was successfully created.') }
        format.json { render json: @incident, status: :created, location: @incident }
      else
        format.html { render action: "new" }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /incidents/1
  # PUT /incidents/1.json
  def update
    @incident = Incident.find(params[:id])

    respond_to do |format|
      if @incident.update_attributes(params[:incident])
        format.html { redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident = Incident.find(params[:id])
    @incident.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end
end

app/views/incidents/_form.html.erb
<%= form_for(@incident) do |f| %>
  <% if @incident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

      <ul>
      <% @incident.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="field">
    DESCRIPTION:<BR/>
    <%= f.text_field :description %>
  </div>
  <div class="field">
		LATITUDE:<BR />
    <%= f.text_field :lat %>
  </div>
	<div class="field">
    LONGITUDE:<BR />
    <%= f.text_field :lon %>
	</div>
  <div class="field">
    DATE:<BR />
    <%= f.datetime_select :this_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incidents/edit.html.erb
<h1>Editing incident</h1>

<%= render 'form' %>

<%= link_to 'Show', @incident %> |
<%= link_to 'Back', incidents_path %>

app/views/incidents/index.html.erb
<h1>Listing incidents</h1>

<table>
  <tr>
    <th>This date</th>
    <th>Description</th>
    <th>Latitude</th>
    <th>Longitude</th>
	<th></th>
	<th></th>
    <th></th>
  </tr>

<% @incidents.each do |incident| %>
  <tr>
    <td><%= incident.this_date %></td>
    <td><%= incident.description %></td>
	<td><%= incident.lat %></td>
	<td><%= incident.lon %></td>
    <td><%= link_to 'Show', incident %></td>
    <td><%= link_to 'Edit', edit_incident_path(incident) %></td>
    <td><%= link_to 'Destroy', incident, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Incident', new_incident_path %>

app/views/incidents/new.html.erb
<h1>NEW INCIDENT</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/incidents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>This date:</b>
  <%= @incident.this_date %>
</p>

<p>
  <b>Description:</b>
  <%= @incident.description %>
</p>


<%= link_to 'Edit', edit_incident_path(@incident) %> |
<%= link_to 'Back', incidents_path %>