config/routes.rb
Erms::Application.routes.draw do
    
    root :to => 'home#index'
    get "log_in" => "sessions#new", :as => "log_in"
    get "log_out" => "sessions#destroy", :as => "log_out"
    get "/resources/search" => "resources#search", :as => "search"
    get "/resources/status" => "resources#status", :as => "status"
    get "/resources/report" => "resources#report", :as => "report"
    match "/requests/deploy" => "requests#deploy", :as => "deploy"
    match "/requests/deploy_request" => "requests#deploy_request", :as => "deploy_request"
    match "/requests/make_request" => "requests#make_request", :as => "make_request"
    match "/requests/return" => "requests#return", :as => "return"
    match "/requests/reject" => "requests#reject", :as => "reject"
    match "/resources/search_results" => "resources#search_results", :as => "search_results"
    resources :sessions    
    resources :users

    resources :resources

    resources :requests

    resources :municipalities

    resources :incidents

    resources :governmentagencies

    resources :esfs

    resources :costperitems

    resources :companies

    resources :capabilities

    resources :addesfs

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :resource
  belongs_to :incident
  validates_presence_of :resource_id, :incident_id
  def incident
      return Incident.find_by_sql("select * from incidents where id = #{self.incident_id}")
  end
  def resource
      return Resource.find_by_id("select * from resources where id = #{self.resource_id}")
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  
  
    def make_request
        puts params
        r = Request.new
        r.resource_id = params[:r_id]
        r.incident_id = params[:i_id]
        if current_user.id == Resource.find_by_sql("SELECT * FROM resources WHERE id = #{params[:r_id]}").first.user_id
            r.status = "In Use"
        else
            r.status = "Requested"
        end
        if r.save
            redirect_to "/resources/status", :notice => "Successfully requested"
        else
            redirect_to "/resources/status", :notice => "Error requesting"
        end
    end
    def deploy
        puts params
        r = Request.new
        r.resource_id = params[:r_id]
        r.incident_id = params[:i_id]
        r.status = "In Use"
        if r.save
            redirect_to "/resources/status", :notice => "Successfully deployed"
        else
            redirect_to "/resources/status", :notice => "Error deploying"
        end
    end
    
    def return
        rq = Request.find_by_sql("SELECT * FROM requests WHERE id = #{params[:rq_id]}").first
        @i_id = rq.incident_id
        @r_id = rq.resource_id
        rq.destroy
        Request.find_by_sql("SELECT * FROM requests ORDER BY created_at ASC").each do |rq|
            if rq.i_id == @i_id && rq.r_id == @r_id && rq.status = "Requested"
                rq.status = "In Use"
                if rq.save
                    redirect_to "/resources/status", :notice => "Successfully returned"
                else
                    redirect_to "/resources/status", :notice => "Error returning"
                end
            end
        end
        
        redirect_to "/", :notice => "Successfully returned"

    end
    def reject
        Request.find_by_sql("SELECT * FROM requests WHERE id = #{params[:rq_id]}").first.destroy
        redirect_to "/resources/status", :notice => "Successfully destroyed"
    end
    def deploy_request
        rq = Request.find_by_id(params[:id])
        rq.status = "In Use"
        if rq.save
            redirect_to "/resources/status", :notice => "Successfully requested"
        else
            redirect_to "/resources/status", :notice => "Error requesting"
        end
    end
  
  
  
  
  
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :ok }
    end
  end
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :incident %><br />
    <%= f.text_field :incident %>
  </div>
  <div class="field">
    <%= f.label :resource %><br />
    <%= f.text_field :resource %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>

<table>
  <tr>
    <th>Incident</th>
    <th>Resource</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requests.each do |request| %>
  <tr>
    <td><%= request.incident %></td>
    <td><%= request.resource %></td>
    <td><%= request.status %></td>
    <td><%= link_to 'Show', request %></td>
    <td><%= link_to 'Edit', edit_request_path(request) %></td>
    <td><%= link_to 'Destroy', request, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Incident:</b>
  <%= @request.incident %>
</p>

<p>
  <b>Resource:</b>
  <%= @request.resource %>
</p>

<p>
  <b>Status:</b>
  <%= @request.status %>
</p>


<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>