config/routes.rb
Erms::Application.routes.draw do
    
    root :to => 'home#index'
    get "log_in" => "sessions#new", :as => "log_in"
    get "log_out" => "sessions#destroy", :as => "log_out"
    get "/resources/search" => "resources#search", :as => "search"
    get "/resources/status" => "resources#status", :as => "status"
    get "/resources/report" => "resources#report", :as => "report"
    match "/requests/deploy" => "requests#deploy", :as => "deploy"
    match "/requests/deploy_request" => "requests#deploy_request", :as => "deploy_request"
    match "/requests/make_request" => "requests#make_request", :as => "make_request"
    match "/requests/return" => "requests#return", :as => "return"
    match "/requests/reject" => "requests#reject", :as => "reject"
    match "/resources/search_results" => "resources#search_results", :as => "search_results"
    resources :sessions    
    resources :users

    resources :resources

    resources :requests

    resources :municipalities

    resources :incidents

    resources :governmentagencies

    resources :esfs

    resources :costperitems

    resources :companies

    resources :capabilities

    resources :addesfs

end

app/views/resources/_capability_fields.html.erb
<div class="field">
	CAPABILITY:<BR />
	<%= f.text_field :capability %>
	<%= f.hidden_field :_destroy %>
        <div style = "color: red; float:right;margin-right: 400px"><%= link_to_remove_fields "REMOVE", f %></div>
</div>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    RESOURCE:<BR />
    <%= f.text_field :name, :size => 20 %>
  </div>
  <div class="field">
    MODEL:<BR />
    <%= f.text_field :model, :size => 20 %>
  </div>
  <div class="field">
    COST:<BR />
    $<%= f.number_field :cost, :size => 8 %> per <%= f.text_field :costperitem, :size => 10 %>
  </div>
  <div class="field">
    LATITUDE:<br />
    <%= f.text_field :lat, :size => 20 %> 
  </div>
  <div class ="field">
    LONGITUDE:<br />
    <%= f.text_field :lon, :size => 20 %>
  </div>
  <div class="field">
    PRIMARY ESF:<BR />
    <%= f.select(:esf_id, Esf.all.collect {|e| [e.description, e.id]}, :prompt => "--Select a primary ESF--" ) %>
  </div>
  <div class="field">
		ADDITIONAL ESFS: <BR />
		<%= select_tag 'add_esfs[]', options_for_select(Esf.all.collect {|e| [e.description, e.id]}), :multiple=> true, :size => 6 %>
	</div>
	<%= f.fields_for :capabilities do |builder| %>
		<%= render "capability_fields", :f => builder %>
	<% end %>
	<div class="field"><%= link_to_add_fields "ADD CAPABILITY", f, :capabilities %></div><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Model</th>
    <th>Cost</th>
    <th>Lat</th>
    <th>Lon</th>
    <th>User</th>
    <th>Esf</th>
    <th>Costperitem</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.name %></td>
    <td><%= resource.model %></td>
    <td><%= resource.cost %></td>
    <td><%= resource.lat %></td>
    <td><%= resource.lon %></td>
    <td><%= resource.user.name %></td>
    <td><%= resource.esf.description %></td>
    <td><%= resource.costperitem.item %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>NEW RESOURCE</h1>
<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/resources/report.html.erb
<table>
	<tr>
		<th>#</th>
		<th>Primary Emergency Support Function</th>
		<th>Total Resources</th>
		<th>Resources in Use</th>
	</tr>
	<% @esfs.each do |esf| %>
		<tr>
			<td><%= esf.id %></td>
			<td><%= esf.description %></td>
			<td><%= Resource.where(:esf_id => esf.id).size %></td>
			<td><% count = 0; Request.all.each do |rq|%>
				<% if rq.status == "In Use" && Resource.find_by_id(rq.resource_id).esf_id == esf.id %>
					<% count = count + 1 %>
					<% end %>
					<% end %>
					<%= count %></td>
		</tr>
		<% end %>
</table>

app/views/resources/search.html.erb
<h1>SEARCH FOR RESOURCES</h1>
<%= form_tag "/resources/search_results" do %>
	<div class="field">
		<%= label_tag "Keyword" %>
		<%= text_field_tag :keyword %>
	</div>
	<div class ="field">
		<%= label_tag "ESF" %>
		<%= select(:all, :esf_id, Esf.all.collect {|e| [e.description, e.id]}, :include_blank => true) %>
	</div>
	<div class="field">
		<%= label_tag "Distance away" %>
		<%= text_field_tag :distance %> kilometers
	</div>
	<div class="field">
		<%= label_tag "Incident" %>
		<%= select(:all, :incident_id, @incidents.all.collect{|i| [i.description, i.id]}, :include_blank => true) %>
	</div>
	<div class="button"><%= submit_tag "Search!" %></div>
<% end %>

app/views/resources/search_results.html.erb
<h1>Search result</h1>
<% @i = @final_result[0]; %>
<% @results = @final_result[1] %>
<%= @i.description if !@i.blank? %>
<% inuse = false %>
<% if !@results.blank? %>
<table>
<tr>
	<th>Name</th>
	<th>Owner</th>
	<th>Cost</th>
	<% if !@i.blank? %>
		<th>Distance</th>
		<th>In Use?</th>
		<th>Action</th>
	<% end %>
</tr>
<% @results.each do |r| %>
	<tr>
		<td><%= r.name %></td>
		<td><%= r.user.name %></td>
		<td><%= "#{r.cost} per #{r.costperitem.item}" %></td>
		<% if !@i.blank? %>
			<td><%= r.distanceFrom(@i) %> km</td>
			<% if r.inUse? %>
				<td>Yes</td>
			<% else %>
				<td>No</td>
			<% end %>
			<% if r.user_id == current_user.id %>
				<td><%= link_to "Deploy", deploy_path(:r_id => r.id, :i_id => @i.id)%></td>
			<% else %>
				<td><%= link_to "Request", make_request_path(:r_id => r.id, :i_id => @i.id ) %></td>
			<% end %>
	<% end %>
	</tr>
<% end %>
</table>
<% else %>
No search results
<% end %><br />
<%= link_to "Search again", "/resources/search" %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resource.name %>
</p>

<p>
  <b>Model:</b>
  <%= @resource.model %>
</p>

<p>
  <b>Cost:</b>
  <%= @resource.cost %>
</p>

<p>
  <b>Lat:</b>
  <%= @resource.lat %>
</p>

<p>
  <b>Lon:</b>
  <%= @resource.lon %>
</p>

<p>
  <b>User:</b>
  <%= @resource.user %>
</p>

<p>
  <b>Esf:</b>
  <%= @resource.esf %>
</p>

<p>
  <b>Costperitem:</b>
  <%= @resource.costperitem %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/resources/status.html.erb
<h1 style="padding-bottom: 5px; font-size: 20px">RESOURCES IN USE</h1>
<% if !@user_resource_requests.blank?%>
<table>
<tr>
	<th>Resource Name</th>
	<th>Incident</th>
	<th>Owner</th>
	<th>Action</th>
</tr>
<% @user_resource_requests.each do |rq| %>
	<tr>
		<td><%= Resource.find_by_sql("SELECT * FROM resources WHERE id = #{rq.resource_id}").first.name %></td>
		<td><%= Incident.find_by_sql("SELECT * FROM incidents WHERE id = #{rq.incident_id}").first.description %></td>
		<td><%= User.where(:id => Resource.where(:id => rq.resource_id).first.user_id).first.name %></td>
		<td><%= link_to "Return", return_path(:rq_id => rq.id) %>
	</tr>
<% end %>
</table>
<% else %>
No resource requests
<% end %>
<div style="padding-bottom: 10px"></div>
<h1 style="padding-bottom: 5px; font-size: 20px">REQUESTS SENT BY ME</h1>
<% if !@requests_sent.blank? %>
<table>
<tr>
	<th>Resource Name</th>
	<th>Incident</th>
	<th>Owner</th>
	<th>Action</th>
</tr>
<% @requests_sent.each do |rq| %>
	<tr>
		<td><%= Resource.find_by_sql("SELECT * FROM resources WHERE id = #{rq.resource_id}").first.name %></td>
		<td><%= Incident.find_by_sql("SELECT * FROM incidents WHERE id = #{rq.incident_id}").first.description %></td>

		<td><%= User.where(:id => Resource.where(:id => rq.resource_id).first.user_id).first.name %></td>
		<td><%= link_to "Cancel", rq, method: :delete %></td>
	</tr>
<% end %>
</table>
<% else %>
No resource requests
<% end %>
<div style="padding-bottom: 10px"></div>
<h1 style="padding-bottom: 5px; font-size: 20px">REQUESTS SENT BY OTHERS</h1>
<% if !@requests_received.blank? %>
<table>
<tr>
	<th>Resource Name</th>
	<th>Incident</th>
	<th>Owner</th>
	<th colspan="2">Action</th>
</tr>
<% @requests_received.each do |rq| %>
	<tr>
		<td><%= Resource.find_by_sql("SELECT * FROM resources WHERE id = #{rq.resource_id}").first.name %></td>
		<td><%= Incident.find_by_sql("SELECT * FROM incidents WHERE id = #{rq.incident_id}").first.description %></td>
		<td><%= User.where(:id => Resource.where(:id => rq.resource_id).first.user_id).first.name %></td>
		<td>
		<% if rq.status == "In Use" %>
			Currently in Use
			<% else %>
			<%= link_to "Deploy", deploy_request_path(:id => rq.id) %>
			<% end %></td>
		<td><%= link_to "Reject", reject_path(:rq_id => rq.id) %></td>
	</tr>
<% end %>
</table>
<% else %>
No resource requests
<% end %>